**독립성 검정 - 카이제곱 검정**

* 범주형 데이터에 대한 통계적 가설 검정을 수행
* 두 개 이상의 범주형 변수 간의 관계를 분석하거나 관찰된 빈도와 기대 빈도 사이의 차이를 확인하는데 활용

**stats.chi2_contingency()**
1. from scipy.stats import chi2_contingency
2.  범주형 데이터를 pd.crosstab(df.col1, df.col2) 교차표를 만듦
3. chi, p_val, df, expected 순으로 변수를 받음

In [ ]:
# 타이타닉 데이터셋을 이용하여 다음 아래 질문에 답하시오
# (1) 생존 여부와 성별 간의 독립성 검정
# (2) 생존 여부와 연령대 간의 독립성 검정

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/dataset/main/titanic.csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
table = pd.crosstab(df['Sex'],df['Survived'])

In [ ]:
from scipy.stats import chi2_contingency

chi, p_val, df, exp = chi2_contingency(table)
print(chi,p_val,df,exp)

# p_val가 매우 작으므로 귀무가설 기각 => 연관성이 있다

260.71702016732104 1.1973570627755645e-58 1 [[193.47474747 120.52525253]
 [355.52525253 221.47474747]]
260.71702016732104 1.1973570627755645e-58

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# 대응표본의 평균 차이 검정(t- 검정)


*   두 집단의 평균 차이를 비교하고, 이 차이가 통계적으로 유의미한지 확인


* from scipy import stats

* 귀무가설 : 차이가 없다
* 대립가설 : 차이가 있디

In [ ]:
from scipy import stats

df1 = [7,3,4,5,2,1,6,6,5,4]
df2 = [8,4,5,6,2,3,6,8,6,5]

#diff = df1-df2

t_stat, p_value = stats.ttest_rel(df1,df2)
print(t_stat,p_value)

# 귀무가설 기각 :

-4.743416490252569 0.0010538712570165528

# 정규성 검정

In [1]:
from scipy import stats

df = [7,3,4,5,2,1,6,6,5,4]

p_value = stats.shapiro(df)
print(p_value)

# 귀무가설 : 정규분포를 따른다
# 대립가설 : 정규분포를 따르지 않는다

ShapiroResult(statistic=0.9644595362997496, pvalue=0.8352703969642297)